### ISSUE TITLE
Bot.hears doesn't work on rooms with others people

### ISSUE THREAD

**Issue by tloyau** [nmarus/flint#9]
Hi men, i have problem with flint.

I have developed a bot, when I speak with him on 1v1, it’s work very well but when I add him on a room with some others people,

the « flint.hears(‘/hello’,…}); » doesn’t work when I say « @mybot /hello »

in the logs, the message detected is « @mybot /hello » and not « /hello »

So, how do you delete the name mentioned of the bot, so that the bot can interpret the « /hello »

thanks in advance

**Comment by nmarus** [comment]
This is fixed in 4.3.2. Cisco recently changed the bot naming convention and the function that was in place to determine if flint was running as a user or as a bot was broken.
